"""
该类包含了一些用于操控演员（actors）的基本操作。所有演员的行为都应该是这些操作的组合
"""

import carla
from safebench.scenario.scenario_manager.carla_data_provider import CarlaDataProvider
from safebench.util.pid_controller import VehiclePIDController
from safebench.scenario.tools.scenario_utils import calculate_distance_locations


class ScenarioOperation(object):
    """
        This class defines some atomic operation for actors. All actor's behaviors should be combination of these operations
    """

    def __init__(self):
        self.other_actors = []
        self.background_actors = []
        self.need_accelerated = False
        self.vehicle_controller = {}

    def initialize_vehicle_actors(self, actor_transform_list, actor_type_list):
        other_actor_list = []
        if len(actor_type_list) != len(actor_transform_list):
            print("Error caused by length match:", len(actor_type_list), len(actor_transform_list))
        else:
            for i in range(len(actor_type_list)):
                try:
                    actor = CarlaDataProvider.request_new_actor(actor_type_list[i], actor_transform_list[i])
                    if actor is not None:
                        actor.set_simulate_physics(enabled=True)
                    other_actor_list.append(actor)
                except:
                    print(f"Failed generated by actor {actor_type_list[i]}")
                    continue

        self.other_actors = other_actor_list
        self._init_vehicle_controller()
        return self.other_actors

    def initialize_background_actors(self, actor_transform_list, actor_type_list):
        other_actor_list = []
        if len(actor_type_list) != len(actor_transform_list):
            print("Error caused by length match:", len(actor_type_list), len(actor_transform_list))
        else:
            for i in range(len(actor_type_list)):
                try:
                    actor = CarlaDataProvider.request_new_actor(actor_type_list[i], actor_transform_list[i], autopilot=True)
                    if actor is not None:
                        actor.set_simulate_physics(enabled=False)
                    other_actor_list.append(actor)
                except:
                    print(f"Failed generated by actor {actor_type_list[i]}")
                    continue

        # self.background_actors = other_actor_list
        self.other_actors.extend(other_actor_list)
        return self.other_actors

    def _init_vehicle_controller(self):
        # 为每个车辆演员初始化一个 PID 控制器，用于控制车辆的横向和纵向运动
        fps = 30
        _dt = 1.0 / fps
        _args_lateral_dict = {'K_P': 1.95, 'K_I': 0.05, 'K_D': 0.2, 'dt': _dt}
        _args_longitudinal_dict = {'K_P': 1.0, 'K_I': 0.05, 'K_D': 0, 'dt': _dt}
        for i in range(len(self.other_actors)):
            if(isinstance(self.other_actors[i], carla.Vehicle)):
                cur_id = self.other_actors[i].id
                cur_controller = VehiclePIDController(self.other_actors[i], args_lateral=_args_lateral_dict, args_longitudinal=_args_longitudinal_dict)
                self.vehicle_controller[cur_id] = cur_controller

    def go_straight(self, target_speed, i, throttle_value=1.0, break_value=1.0, steering=0.0):
        control = self.other_actors[i].get_control()
        if CarlaDataProvider.get_velocity(self.other_actors[i]) <= target_speed:
            self.need_accelerated = True
        else:
            self.need_accelerated = False
        if self.need_accelerated:
            control.throttle = throttle_value
            control.brake = 0.0
        else:
            control.throttle = 0.0
            control.brake = break_value
        control.steer = steering
        self.other_actors[i].apply_control(control)

    def walker_go_straight(self, target_speed, i):
        # 控制行人直行，设置行人的速度和方向
        # 注意：actor.is_alive 只反映 Python 侧本地状态，无法检测服务端因碰撞
        # 触发的 actor 销毁。真正的防护依赖 is_invincible=true 防止 walker 死亡，
        # 以及 carla_data_provider 里的 world.get_actors() 过滤。
        actor = self.other_actors[i]
        if actor is None:
            return
        control = actor.get_control()
        control.speed = target_speed
        control.direction = CarlaDataProvider.get_transform(actor).get_forward_vector()
        # control.throttle = 1.0
        actor.apply_control(control)

    def drive_to_target_followlane(self, i ,target_transform, target_speed):
        # 'i' represents id/order of specific actor in other_actors list
        cur_vehicle_control = self.vehicle_controller.get(self.other_actors[i].id)
        control = cur_vehicle_control.run_step(target_speed, target_transform)
        self.other_actors[i].apply_control(control)

    def drive_to_nofollowlane(self, i, location_queue, target_speed):
        # 控制车辆不沿车道行驶到目标位置，使用位置队列来逐步接近目标
        cur_vehicle_control = self.vehicle_controller.get(self.other_actors[i].id)
        cur_actor_location = CarlaDataProvider.get_location(self.other_actors[i])
        target_location = None
        if (len(location_queue) > 0):
            target_location = location_queue[0]
        if(target_location):
            if(calculate_distance_locations(target_location, cur_actor_location) < 5):
                location_queue.pop(0)
            else:
                target_location = target_location
        target_waypoint = CarlaDataProvider.get_map().get_waypoint(cur_actor_location)
        control = cur_vehicle_control.run_step(target_speed, target_waypoint)
        self.other_actors[i].apply_control(control)

    def brake(self, actor):
        control = actor.get_control()
        control.throttle = 0.0
        control.brake = 1.0
        actor.apply_control(control)

    def roll_over(self):
        pass
