scenario_type_dir: 'safebench/scenario/scenario_data/TsimShaTsui-1029-3' # 定义功能场景的路径
scenario_type: 'standard_scenario_01.json'  # json文件,定义了功能场景的类型,包括了场景的索引id,功能场景类别,发生在哪一个Route id上
scenario_category: 'planning'
policy_type: 'standard'  # 标准测试方法可以理解为,使用scenario_runner范式来定义的场景

# 定义动态交通场景发生的地图、天气等参数
route_dir: 'safebench/scenario/scenario_data/TsimShaTsui-1029-3'
scenario_id: 1
route_id: null

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

# not useful
model_path: ''
standard_action: False
buffer_capacity: 100
eval_in_train_freq: 10
save_freq: 10
train_episode: 100

